<a href="https://colab.research.google.com/github/ilyessdridi/data-preparation/blob/main/DataPreparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#Pour afficher la version de  numpy : mathematical operations, arrays, numbers.
print(f"numpy version {np.__version__}")

import pandas as pd
# Pour afficher la version de pandas : working with tables/datasets.
print(f"pandas version {pd.__version__}")

numpy version 2.1.3
pandas version 2.2.3

In [ ]:
import numpy as np # calculations
import pandas as pd #datasets/tables
import matplotlib.pyplot as plt #graphs
from numpy import isnan  # checks if a value is missing
from pandas import read_csv # read csv


## Method (1): Create a Dataframe from multiple series

We start by creating a Pandas series which is like a column in a table with index.

In [ ]:

# Create a series to list students with their age
age = pd.Series([23, 22, 25], index=['Student1', 'Student2', 'Student3'])
print(age)
print("===================================================")
# Create a series to list students with their high
height = pd.Series([155, 175, 168], index=['Student1', 'Student3', 'Student4'])
print(height)

Student1    23
Student2    22
Student3    25
dtype: int64
===================================================
Student1    155
Student3    175
Student4    168
dtype: int64

**A dataframe** can be composed of multiple series, or it can be defined as a collection of series that can be used to analyze data.

In [ ]:
stat = pd.DataFrame({'age': age, 'height': height})
stat

           age  height
Student1  23.0   155.0
Student2  22.0     NaN
Student3  25.0   175.0
Student4   NaN   168.0

## Method (2): Load a Dataframe

In [ ]:
## load dataset from a url
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/horse-colic.csv'
# help to predict whether or not a horse can survive based upon past medical conditions
stat2 = read_csv(url, header=None, na_values='?')
print(stat2.shape)
stat2

(300, 28)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,2,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,NaN,3.0,3.3,3.0,1,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,NaN,NaN,2.0,1,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

In [ ]:
## load dataset from a file on JupyterLab
stat3=pd.read_excel('data.xlsx', header=None, na_values='?')
print(stat3.shape)
stat3

(5, 3)

           0    1       2
0        NaN  age  height
1  Etudiant1   23     155
2  Etudiant2   22     NaN
3  Etudiant3   25     175
4  Etudiant4  NaN     168

## Method(3): Create a Dataframe

In [ ]:
 x=np.nan
 df=pd.DataFrame(
 {   "Type": ['Student1', 'Student2', 'Student3', 'Student4' ],

  "order": [2,10, x, 10],
  "age": [23,x , 25, 0],
  "height": [155, 160, x, 160],
 }
 )
 df

       Type  order   age  height
0  Student1    2.0  23.0   155.0
1  Student2   10.0   NaN   160.0
2  Student3    NaN  25.0     NaN
3  Student4   10.0   0.0   160.0

<p style="font-family: Arial; font-size:1.75em;color:red; font-style:bold"><br>
III.Get information about a dataset</p><br>

In [ ]:
 data = pd.read_csv('titanic.csv')
# titanic data set help to predicts which passengers survived the Titanic shipwreck

In [ ]:
 data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
 data.shape

(891, 12)

In [ ]:
 data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
 data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
 data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
 data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

<p style="font-family: Arial; font-size:1.75em;color:red; font-style:bold"><br>
IV Data Preparation </p><br>

<font color='blue' ><h3>
IV.1. Data Cleaning </p><h3>

## (1): Checking for NAN values

In [ ]:
 df.isnull().values.any()

np.True_

In [ ]:
 df.isnull().sum()

Type      0
order     1
age       1
height    1
dtype: int64

In [ ]:
 df.isnull().sum().sum()

np.int64(3)

In [ ]:
 df.notnull().values.any()

np.True_

In [ ]:
df.notnull().sum().sum()

np.int64(13)

In [ ]:
 df.isna().sum()

Type      0
order     1
age       1
height    1
dtype: int64

In [ ]:
 df.isna().sum().sum()

np.int64(3)

In [ ]:
 df.notna().sum().sum()

np.int64(13)

## (2): Common Methods to Imputing Missing Data

There are different methods that we use to impute missing data such that: Mean strategy, Median technique and Mode technique.\

#### *) Mean strategy

In [ ]:
#One of the technique is mean imputation in which the missing values are replaced with the mean value of the entire feature column
df.fillna(df.mean(numeric_only=True))

       Type      order   age      height
0  Student1   2.000000  23.0  155.000000
1  Student2  10.000000  16.0  160.000000
2  Student3   7.333333  25.0  158.333333
3  Student4  10.000000   0.0  160.000000

#### *) Median technique

In [ ]:
 #Median imputation in which the missing values are replaced with the median value of the entire feature column.
#When the data is skewed, it is good to consider using median value for replacing the missing values.
df.fillna(df.median(numeric_only=True))

       Type  order   age  height
0  Student1    2.0  23.0   155.0
1  Student2   10.0  23.0   160.0
2  Student3   10.0  25.0   160.0
3  Student4   10.0   0.0   160.0

#### *) Mode technique (most frequent value)

In [ ]:

#mode imputation in which the missing values are replaced with the mode value or most frequent value of the entire feature column. When the data is skewed, it is good to consider using mode value for replacing the missing values. For data points such as salary field,
#you may consider using mode for replacing the values
df['height'] = df['height'].fillna(df['height'].mode()[0])
df

       Type  order   age  height
0  Student1    2.0  23.0   155.0
1  Student2   10.0   NaN   160.0
2  Student3    NaN  25.0   160.0
3  Student4   10.0   0.0   160.0

In [ ]:
df['order'] = df['order'].fillna(df['order'].mode()[0])
df

       Type  order   age  height
0  Student1    2.0  23.0   155.0
1  Student2   10.0   NaN   160.0
2  Student3   10.0  25.0   160.0
3  Student4   10.0   0.0   160.0

<font color='blue' ><h3>
IV.2. Feature selection </p><h3>

Feature selection is used to determine the best set of features for building useful models.

In [ ]:
# load data
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
# The objective of the dataset is to diagnostically predict whether or not a patient has diabetes,
dataframe = pd.read_csv(url, names=names)
dataframe

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

After loading the dataframe, we convert it to a NumPy array to speed up the
calculation with separation the features and labels.

In [ ]:
array = dataframe.values
X1 = array[:,0:8]
Y1 = array[:,8]
print(X1)
print(Y1)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0.
 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1.
 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.
 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0.
 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1.
 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.
 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0.]

In [ ]:
# Import the necessary libraries first
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [ ]:
# # Feature extraction
test = SelectKBest(score_func=chi2, k=4)
## chi2: Chi-squared stats of non-negative features for classification tasks.
fit = test.fit(X1, Y1)

fit.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [ ]:
# # Summarize scores
Listfeatures= ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age']
print(Listfeatures)
print('================================================================================')
np.set_printoptions(precision=3)
print(fit.scores_)

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age']
================================================================================
[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]

In [ ]:
features = fit.transform(X1)
# # Summarize selected features
print(features[0:5,:])

[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]

### Interpretation:

You can now see the scores for each attribute and the 4 selected attributes (those with the highest scores)are: test, plas, age, mass.

These scores will further help you to determine the best features to train your model.

<font color='blue' ><h3>
IV.3. Data transformation </p><h3>

## A.Categorical features

Transforming categorical data is an essential step during data preprocessing. sklearn’s machine learning library require the input dataset to always have numeric values it does not support categorical data.

It is necessary to convert categorical features to a numerical representation.

Before you start transforming your data, it is important to figure out if the feature you’re working on is ordinal (as opposed to nominal). An ordinal feature is best described as a feature with  ordered categories.

Once you know what type of categorical data you’re working on, you can pick a suiting transformation tool. In sklearn that will be a OrdinalEncoder or LabelEncoder for ordinal data, and a OneHotEncoder for nominal data.

Let’s consider a simple example to demonstrate how both classes are working. Create a dataframe with four entries and three features: sex, blood type and education level.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
X1 = pd.DataFrame(
    np.array(['M', 'O-', 'medium',
             'M', 'O-', 'high',
              'F', 'O+', 'high',
              'F', 'AB', 'low']
            )
              .reshape((4,3)))
X1.columns = ['sex', 'blood_type', 'edu_level']

In [ ]:
 X1

  sex blood_type edu_level
0   M         O-    medium
1   M         O-      high
2   F         O+      high
3   F         AB       low

### 1.Ordinal Feature
Looking at the dataframe, you should notice education level is the only ordinal feature (it can be ordered and the distance between the categories is not known). We’ll start with encoding this feature with the OrdinalEncoder class. Import the class and create a new instance. Then update the education level feature by fitting and transforming the feature to the encoder. The result should look as below.

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
X1.edu_level = encoder.fit_transform(X1.edu_level.values.reshape(-1, 1))

In [ ]:
X1

  sex blood_type  edu_level
0   M         O-        2.0
1   M         O-        0.0
2   F         O+        0.0
3   F         AB        1.0

Notice that we have a rather annoying issue here: our missing value is encoded as a separate class (3.0). Looking thoroughly at the documentation reveals that there is no solution for this issue yet. A good sign is that the sklearn developers are discussing the possibilities of implementing a suiting solution.
Another problem is that the order of our data is not respected. This can luckily be solved by passing an ordered list of unique values for the feature to the categories parameter.

In [ ]:
X = pd.DataFrame(
    np.array(['M', 'O-', 'medium',
             'M', 'O-', 'high',
              'F', 'O+', 'high',
              'F', 'AB', 'low']
            )
              .reshape((4,3)))


X.columns = ['sex', 'blood_type', 'edu_level']

In [ ]:
encoder = OrdinalEncoder(categories=[[ 'low', 'medium', 'high']])

In [ ]:
X.edu_level = encoder.fit_transform(X.edu_level.values.reshape(-1, 1))

X

  sex blood_type  edu_level
0   M         O-        1.0
1   M         O-        2.0
2   F         O+        2.0
3   F         AB        0.0

#### OrdinalEncoder vs LabelEncoder

OrdinalEncoder is for 2D data with the shape (n_samples, n_features)

LabelEncoder is for 1D data with the shape (n_samples,))

### 2. Nominal Features


The most popular way to encode nominal features is one-hot-encoding. Essentially, each categorical feature with n categories is transformed into n binary features.

Start with importing the OneHotEncoder class and creating a new instance with the output data type set to integer

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(dtype=int, sparse_output=True)

Then, fit and transform our two nominal categoricals. The output of this transformation will be a sparse matrix, which we will transform the matrix to an array (.toarray()) before we can pour it into a dataframe. Assign column names and the output is ready to be added to the other data (edu_level feature).

In [ ]:

nominals = pd.DataFrame(
    onehot.fit_transform(X[['sex', 'blood_type']]).toarray(),
    columns=['F', 'M', 'AB','O+', 'O-'])
nominals['edu_level'] = X.edu_level

Compare the output (nominals) to our original data to make sure everything came through the right way.

In [ ]:
nominals

   F  M  AB  O+  O-  edu_level
0  0  1   0   0   1        1.0
1  0  1   0   0   1        2.0
2  1  0   0   1   0        2.0
3  1  0   1   0   0        0.0

In [ ]:
X

## B. Feature scaling



Feature scaling is a very important step in the preprocessing pipeline.

Before applying any scaling operation it is very important to split your data into a train set and a test set. If you start scaling before, your training (and test) data might end up scaled around a mean value (see below) that is not actually the mean of the train or test data, and go past the whole reason why you're scaling in the first place.



Standardization is a transformation that centers the data by removing the mean value of each feature and then scale it by dividing (non-constant) features by their standard deviation. After standardizing data the mean will be zero and the standard deviation one.
Standardization can drastically improve the performance of models. For instance, many learning algorithms (such as Support Vector Machines) assume that all features are centered around zero and have variance in the same order.
Depending on your needs and data, sklearn provides a bunch of scalers: StandardScaler, MinMaxScaler, MaxAbsScaler and RobustScaler.

### Methode (1) Standardization (Standard Scaler)


Sklearn its main scaler, the StandardScaler, uses a strict definition of standardization to standardize data. It purely centers the data by using the following formula,

# x_scaled = (x - u) / s

## where u is the mean and s is the standard deviation.

Let’s take a look at our example to see this in practice.
Import the StandardScaler class and create a new instance. Then, fit and transform the scaler to feature 3.

In [ ]:
Y = pd.DataFrame(
    np.array([5,7,8, np.nan, np.nan, np.nan, -5,
              0,25,999,1,-1, np.nan, 0, np.nan])\
              .reshape((5,3)))
Y.columns = ['f1', 'f2', 'f3'] #feature1, feature 2, feature 3
Y

      f1   f2    f3
0    5.0  7.0   8.0
1    NaN  NaN   NaN
2   -5.0  0.0  25.0
3  999.0  1.0  -1.0
4    NaN  0.0   NaN

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(Y.f3.values.reshape(-1, 1))

array([[-0.247],
       [   nan],
       [ 1.33 ],
       [-1.082],
       [   nan]])



### Method(2): Normalization:

Data normalization is a fundamental component, It entails transforming the data, or turning the source data into another format that enables for successful data processing.

The MinMaxScaler transforms features by scaling each feature to a given range. This range can be set by specifying the feature_range parameter (default at $(0,1)$).

This scaler works better for cases where the distribution is not Gaussian or the standard deviation is very small. However, it is sensitive to outliers, so if there are outliers in the data, you might want to consider another scaler.

$$x\_scaled = \dfrac{(x-min(x))}{(max(x)–min(x))}$$

#### Method 1:  Manual Computation

In [ ]:
# import pandas as pd

# # data frame containing the odometer reading (km) and the fuel economy (km/l) of second-hand cars
# df_cars = pd.DataFrame([[120000, 11], [250000, 11.5], [175000, 15.8], [350000, 17], [400000, 10]],
#                        columns=['odometer_reading', 'fuel_economy'])

# df_cars

In [ ]:
# df_cars.plot(kind='density',figsize=(13,5))
# plt.title('All variables with different scales', fontsize=20)
# plt.show()

In [ ]:
# # apply the min-max scaling in Pandas using the .min() and .max() methods
# def min_max_scaling(df):
#     # copy the dataframe
#     df_norm = df.copy()
#     # apply min-max scaling
#     for column in df_norm.columns:
#         df_norm[column] = (df_norm[column] - df_norm[column].min()) / (df_norm[column].max() - df_norm[column].min())

#     return df_norm

# # call the min_max_scaling function
# df_cars_normalized = min_max_scaling(df_cars)

# df_cars_normalized

In [ ]:
# df_cars_normalized.plot(kind='density',figsize=(13,5))
# plt.title('All variables with same scales', fontsize=20)
# plt.show()

#### Method 2:  Using MinMaxScaler

In [ ]:
# df_cars.columns

In [ ]:
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler(feature_range=(0,1))
# df_cars_normalized2=scaler.fit_transform(df_cars)

In [ ]:
# df_cars_normalized2

#####  <font color='purple' > When Should You Use Normalization and Standardization:
                                                                                       
Normalization is a good technique to use when you do not know the distribution of your data or when you know the distribution is not Gaussian (a bell curve). Normalization is useful when your data has varying scales and the algorithm you are using does not make assumptions about the distribution of your data, such as k-nearest neighbors and artificial neural networks.

Standardization assumes that your data has a Gaussian (bell curve) distribution. This does not strictly have to be true, but the technique is more effective if your attribute distribution is Gaussian. Standardization is useful when your data has varying scales and the algorithm you are using does make assumptions about your data having a Gaussian distribution, such as linear regression, logistic regression, and linear discriminant analysis.

<font color='blue' ><h3>
IV.4.  Dimensionality reduction </p><h3>


The dimensionality of a dataset is defined as the number of input variables or characteristics.


Dimensionality reduction techniques are those that lower the number of variables in a dataset.


For data visualization, high-dimensionality statistics and dimensionality reduction techniques are frequently used.
Nonetheless, in applied machine learning, similar strategies can be utilized to reduce a classification or regression dataset in order to better train a predictive model.

## PCA (Principal component Anlysis):
Principal component Anlysis is a dimensionality reduction technique used to reduce the number of predictor variables in a dataset.


PCA is a sort of unsupervised feature extraction in which original variables are integrated and reduced to their most important and descriptive components.

### Method(1): Manual Computation

In [ ]:
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# from numpy import array
# from numpy import mean
# from numpy import cov
# from numpy.linalg import eig

The required work is to reduce the dimension of the stat2 dataset using PCA in two ways:
1. From scratch using manual computation
2. Computing using "pca" command

## DataSet: stat2

In [ ]:
# Missing value imputation

### Step(1): Data centering and reduction

The purpose of this step is to standardize the range of initial continuous variables so that each contributes equally to the analysis.
Mathematically, this can be done by subtracting the mean and dividing by the standard deviation for each value of each variable.
Once standardization is complete, all variables will be transformed to the same scale.

In [ ]:
##Data centering and reduction

### Step(2): COMPUTATION OF THE COVARANCE MATRIX

In [ ]:
# compute the covariance matrix of the centered matrix

#### Step(3): Compute the eigenvectors and eigenvalues of the covariance matrix to identify the principle components.

In [ ]:
# eigenvectors and eigenvalues of covariance matrix

### Step(4): Projection of the initial data on the new axes (the principal components)

In [ ]:
# project data

## Method 2: Computation using "PCA"

In [ ]:

# Principal Component Analysis

In [ ]:
# create the PCA instance


# fit on data: Apply PCA on data

In [ ]:
# access values and vectors/

#Principal components: eigenvectors

print("===================================================")
#Variance proportions associated with the axes: eigenvalues.

===================================================

In [ ]:
# transform data/ Projection

In [ ]:
# PCA scree plot:

In [ ]:
# create the PCA instance

# fit on data: Apply PCA on the data


#Principal components: eigenvectors

print("===================================================")
#Variance proportions associated with the axes: eigenvalues.

print("===================================================")
# transform data/ Projection

===================================================
===================================================